### ISSUE TITLE
Error during generation ONVIF-Monitor example

### ISSUE THREAD

**Issue by wallerka77** [Tereius/ONVIFMonitor#1]
Hello Björn,

I am really sorry that I need your help once again.

Actually I wanted to bother you with this problem, but unfortunately I can't get any further on, because some errors occured.

I have logged this once:
[ONVIF-Monitor-Errors.txt](https://github.com/Tereius/ONVIFMonitor/files/5736490/ONVIF-Monitor-Errors.txt)
[CMakeOutput.log](https://github.com/Tereius/ONVIFMonitor/files/5736489/CMakeOutput.log)

Thanks a lot
Walter

**Comment by Tereius** [comment]
Hi, over the holidays I had a look at the conan recipes and ONVIFMonitor. I got it running on an RaspberryPi Zero W. But I'm not sure if it will run on an RaspberryPi 4 because they switched from the Broadcom GLES2 implementation to the one provided by Mesa (I don't own a RaspberryPi 4 so I can't verify). Furthermore it won't run inside X11 or Wayland because Qt is configured to use the Broadcom EGL implementation.

How to build:
* Install a recent Linux distro on a x86 (virtual)machine
* Install build essentials (gcc, cmake, python3, conan, ...) via package manager of your distro
* add following conan remotes: `conan remote add tereius https://api.bintray.com/conan/tereius/public-conan && conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan`
* Checkout ONVIFMonitor and cd into the git root dir: `git clone https://github.com/Tereius/ONVIFMonitor.git && cd ONVIFMonitor`
* Download following conan profile: `wget https://raw.githubusercontent.com/Tereius/conan-Qt/master/buildProfiles/raspbian.profile`
* Now execute: `conan create ./ tereius/stable -pr raspbian.profile --build outdated`

How to deploy:
* If everything was build successfully you have to copy all shared libraries to the RaspberryPi
* Execute again: `conan create ./ tereius/stable -pr raspbian.profile --build outdated` and you should see something like:
```
Installing package: ONVIFMonitor/1.0.0@tereius/stable
Requirements
    ONVIFMonitor/1.0.0@tereius/stable from local cache - Cache
    OpenSSL/1.1.1b@tereius/stable from 'Tereius' - Cache
    Qt/5.12.4@tereius/stable from 'Tereius' - Cache
    QtAV/1.13.0-SNAPSHOT@tereius/stable from 'Tereius' - Cache
    ffmpeg/4.2@tereius/stable from local cache - Cache
    libONVIF/1.1.0-SNAPSHOT@tereius/stable from 'Tereius' - Cache
Packages
    ONVIFMonitor/1.0.0@tereius/stable:2c64f09a6889f551bed4494e30db7d2ef9835fe3 - Cache
    OpenSSL/1.1.1b@tereius/stable:13d1db2ccb7b4e7a464e113c4c40669339517a47 - Cache
    Qt/5.12.4@tereius/stable:89a5f344eae98e0d20a111949e174677728f0198 - Cache
    QtAV/1.13.0-SNAPSHOT@tereius/stable:4a5f79175ba301c419286ab17bfa4527c82044cb - Cache
    ffmpeg/4.2@tereius/stable:dfc220b8f43537c37a43975abc05468836bf803c - Cache
    libONVIF/1.1.0-SNAPSHOT@tereius/stable:740cb4487e08636412565b06b31b6ff65a4978fc - Cache

Cross-build from 'Linux:x86_64' to 'Linux:armv6'
Installing (downloading, building) binaries...
OpenSSL/1.1.1b@tereius/stable: Already installed!
ffmpeg/4.2@tereius/stable: Already installed!
Qt/5.12.4@tereius/stable: Already installed!
QtAV/1.13.0-SNAPSHOT@tereius/stable: Already installed!
libONVIF/1.1.0-SNAPSHOT@tereius/stable: Already installed!
ONVIFMonitor/1.0.0@tereius/stable: Already installed!
```
* Under `Packages` we see all six dependencies with their package ids. For each dependency we have to cd into the package folder and copy the libraries and other files to the RaspberryPi via scp like so (replace <user> with your current username on your machine and <rpi-host> with the ip or hostname of you RaspberryPi):
```
cd /home/<user>/.conan/data/ONVIFMonitor/1.0.0/tereius/stable/package/2c64f09a6889f551bed4494e30db7d2ef9835fe3/bin
scp * pi@<rpi-host>:/home/pi
cd /home/<user>/.conan/data/OpenSSL/1.1.1b/tereius/stable/package/13d1db2ccb7b4e7a464e113c4c40669339517a47/lib
scp * pi@<rpi-host>:/home/pi/lib
cd /home/<user>/.conan/data/Qt/5.12.4/tereius/stable/package/89a5f344eae98e0d20a111949e174677728f0198
scp -r lib pi@<rpi-host>:/home/pi/lib
scp -r plugins pi@<rpi-host>:/home/pi/plugins
scp -r qml pi@<rpi-host>:/home/pi/qml
cd /home/<user>/.conan/data/QtAV/1.13.0-SNAPSHOT/tereius/stable/package/4a5f79175ba301c419286ab17bfa4527c82044cb/lib
scp * pi@<rpi-host>:/home/pi/lib
scp -r qml pi@<rpi-host>:/home/pi/qmlQtAv
cd /home/<user>/.conan/data/ffmpeg/4.2/tereius/stable/package/dfc220b8f43537c37a43975abc05468836bf803c
scp -r lib pi@<rpi-host>:/home/pi/lib
cd /home/<user>/.conan/data/libONVIF/1.1.0-SNAPSHOT/tereius/stable/package/740cb4487e08636412565b06b31b6ff65a4978fc
scp -r lib pi@<rpi-host>:/home/pi/lib
```
* Now <b>switch over</b> to the RaspberryPi and create a qt.conf file in `/home/pi`:
```
cd /home/pi
printf "[Paths]\nPrefix = /home/pi" > qt.conf
```
* We have to tell the runtime linker where to search for the shared libraries: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/pi/lib`
* We have to tell Qt where to find the QtAv qml module: `export QML2_IMPORT_PATH=/home/pi/qmlQtAv`
* Now execute `./ONVIFMonitor` from any tty where X11 is not currently running.

Right now no fonts are visible in the GUI because Qt was configured without fontconfig. But I will add a default font later.

**Comment by wallerka77** [comment]
Hello Björn,
according to your explanation there are no fonts in Qt, because Qt was configured without fontconfig.

You wanted to add them a bit later.
Has this been done now?

Thanx

**Comment by Tereius** [comment]
Yes I added a default font.
